# TabXtract - extracts tablature from video and rebuilds it as a PDF.
# Copyright (C) 2026 TabXtract contributors
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See <https://www.gnu.org/licenses/>.
"""Sidecar entry point.

It binds port 0 (the OS picks a free one), generates a random token and emits
both on stdout as a line of JSON that Tauri reads. A fixed port can collide
with another process and is reachable by anything else running on the machine.

It also shuts itself down if the parent process disappears. Tauri kills the
sidecar when the window closes, but if Tauri itself is killed abruptly nobody
does, and an orphaned Python with opencv inside burns CPU indefinitely.
"""
from __future__ import annotations

import argparse
import ctypes
import json
import logging
import logging.handlers
import os
import secrets
import socket
import stat
import sys
import threading
import time

HANDSHAKE_PREFIX = "TABXTRACT_READY "
PARENT_POLL_SECONDS = 2.0


def _parent_alive(pid: int) -> bool:
    if os.name == "nt":
        SYNCHRONIZE = 0x00100000
        handle = ctypes.windll.kernel32.OpenProcess(SYNCHRONIZE, False, pid)  # type: ignore[attr-defined]
        if not handle:
            return False
        # WAIT_TIMEOUT (0x102) means still alive; WAIT_OBJECT_0 means exited.
        alive = ctypes.windll.kernel32.WaitForSingleObject(handle, 0) == 0x102  # type: ignore[attr-defined]
        ctypes.windll.kernel32.CloseHandle(handle)  # type: ignore[attr-defined]
        return alive
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def _watch_parent(pid: int) -> None:
    while True:
        time.sleep(PARENT_POLL_SECONDS)
        if not _parent_alive(pid):
            os._exit(0)


def _stdin_is_pipe() -> bool:
    """stdin is only watched when it is a real pipe.

    If the sidecar is launched with stdin on /dev/null or closed, `readline`
    returns EOF immediately and the watchdog would kill the process a few
    milliseconds after startup. That happened once already, running the frozen
    binary without stdin: it emitted the handshake and died silently.
    """
    try:
        return stat.S_ISFIFO(os.fstat(sys.stdin.fileno()).st_mode)
    except (OSError, ValueError, AttributeError):
        return False


def _watch_stdin() -> None:
    """Second safety net: when the parent dies, the stdin pipe gives EOF.

    It is faster than polling the PID and works the same on all three
    platforms; the polling covers the case where there is no pipe.
    """
    try:
        while sys.stdin.readline():
            pass
    except (OSError, ValueError):
        pass
    os._exit(0)


def setup_logging() -> None:
    """stderr for the Tauri console, plus a small rotating file in the data
    directory. The file is what a user attaches to a bug report: without it,
    "the app failed" is all they can say. 1 MB and one backup is plenty for
    that and never grows unbounded."""
    from .config import log_path

    fmt = logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s")
    root = logging.getLogger()
    root.setLevel(logging.INFO)
    stream = logging.StreamHandler(sys.stderr)
    stream.setFormatter(fmt)
    root.addHandler(stream)
    try:
        file_handler = logging.handlers.RotatingFileHandler(
            log_path(), maxBytes=1_000_000, backupCount=1, encoding="utf-8")
        file_handler.setFormatter(fmt)
        root.addHandler(file_handler)
    except OSError as exc:  # a read-only data dir must not stop the app
        root.warning("could not open the log file: %s", exc)


def main() -> None:
    parser = argparse.ArgumentParser(prog="tabxtract-server")
    parser.add_argument("--host", default="127.0.0.1",
                        help="only 127.0.0.1 makes sense; exposed for tests")
    parser.add_argument("--port", type=int, default=0,
                        help="0 means an ephemeral port chosen by the OS (the normal case)")
    parser.add_argument("--token", default=None,
                        help="handshake token; one is generated by default")
    parser.add_argument("--parent-pid", type=int,
                        default=int(os.environ.get("TABXTRACT_PARENT_PID") or 0))
    args = parser.parse_args()

    token = args.token or secrets.token_urlsafe(32)
    setup_logging()

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    if os.name == "nt":
        # On Windows SO_REUSEADDR lets another process bind the same port and
        # take over the frontend's connections, token included. This forbids it.
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_EXCLUSIVEADDRUSE, 1)  # type: ignore[attr-defined]
    else:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((args.host, args.port))
    sock.listen(128)
    port = sock.getsockname()[1]

    # Without flush, the stdout buffer keeps the line and Tauri waits forever
    # for a port that already exists.
    print(HANDSHAKE_PREFIX + json.dumps({"port": port, "token": token, "pid": os.getpid()}),
          flush=True)

    if args.parent_pid:
        threading.Thread(target=_watch_parent, args=(args.parent_pid,), daemon=True).start()
    if _stdin_is_pipe():
        threading.Thread(target=_watch_stdin, daemon=True).start()

    import uvicorn

    from .main import create_app

    # log_config=None: uvicorn's loggers propagate to the root configured above
    # instead of installing their own handlers.
    # timeout_graceful_shutdown: a request or socket that will not finish must
    # not keep the process alive. Tauri terminates the sidecar on window close
    # and then waits for it; without a bound, a stuck task turns that into a
    # window that closes and a process that stays.
    config = uvicorn.Config(create_app(token), log_level="info", access_log=False,
                            log_config=None, timeout_graceful_shutdown=3)
    uvicorn.Server(config).run(sockets=[sock])


if __name__ == "__main__":
    main()
